from flask import Flask, request, make_response, Response
from collections import Counter
from datetime import datetime, timezone
from functools import wraps
import json
import os
import re
import secrets
import threading

app = Flask(__name__)

MAIN_ORIGIN = "https://blackboard-browser-mot.onrender.com"

# ---------------------------------------------------------------------------
# Lightweight, privacy-conscious usage stats
# ---------------------------------------------------------------------------
# These stats are intentionally kept in memory only:
#   - no IP addresses are stored
#   - no user identifiers are stored
#   - stats reset whenever the app process restarts/redeploys
#
# Set a strong STATS_PASSWORD environment variable in Render before using
# /stats. The browser will prompt for HTTP Basic Auth credentials.
STATS_USERNAME = os.environ.get("STATS_USERNAME", "admin")
STATS_PASSWORD = os.environ.get("STATS_PASSWORD", "")

stats_lock = threading.Lock()
stats = {
    "started_at": datetime.now(timezone.utc),
    "cookie_tests_total": 0,
    "cookie_tests_by_day": Counter(),
    "browsers": Counter(),
    "operating_systems": Counter(),
    "referrers": Counter(),
}


def utc_day():
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def browser_from_user_agent(user_agent):
    ua = user_agent or ""

    # Order matters: Edge and Chrome both include "Chrome" in their UA.
    if "Edg/" in ua:
        return "Edge"
    if "OPR/" in ua or "Opera/" in ua:
        return "Opera"
    if "Firefox/" in ua:
        return "Firefox"
    if "Chrome/" in ua or "CriOS/" in ua:
        return "Chrome"
    if "Safari/" in ua and "Chrome/" not in ua and "Chromium/" not in ua:
        return "Safari"
    return "Other / unknown"


def os_from_user_agent(user_agent):
    ua = user_agent or ""

    if "Windows" in ua:
        return "Windows"
    if "Android" in ua:
        return "Android"
    if "iPhone" in ua or "iPad" in ua or "iPod" in ua:
        return "iOS / iPadOS"
    if "Macintosh" in ua or "Mac OS X" in ua:
        return "macOS"
    if "Linux" in ua:
        return "Linux"
    return "Other / unknown"


def referrer_bucket(referrer):
    if not referrer:
        return "Direct / unavailable"
    if referrer.startswith(MAIN_ORIGIN):
        return "Blackboard Browser MOT"
    return "Other"


def record_cookie_test():
    user_agent = request.headers.get("User-Agent", "")
    referrer = request.headers.get("Referer", "")

    with stats_lock:
        stats["cookie_tests_total"] += 1
        stats["cookie_tests_by_day"][utc_day()] += 1
        stats["browsers"][browser_from_user_agent(user_agent)] += 1
        stats["operating_systems"][os_from_user_agent(user_agent)] += 1
        stats["referrers"][referrer_bucket(referrer)] += 1


def check_stats_auth(username, password):
    if not STATS_PASSWORD:
        return False

    return (
        secrets.compare_digest(username or "", STATS_USERNAME)
        and secrets.compare_digest(password or "", STATS_PASSWORD)
    )


def stats_auth_required(view):
    @wraps(view)
    def wrapped(*args, **kwargs):
        auth = request.authorization

        if not auth or not check_stats_auth(auth.username, auth.password):
            return Response(
                "Stats dashboard is protected. "
                "Set STATS_PASSWORD in Render, then sign in.",
                401,
                {"WWW-Authenticate": 'Basic realm="BB MOT stats"'},
            )

        return view(*args, **kwargs)

    return wrapped


@app.get("/")
def home():
    return "Blackboard Browser MOT cookie helper is running.", 200


@app.get("/cookie-test")
def cookie_test():
    nonce = request.args.get("nonce", "")

    # Only allow the nonce format generated by the MOT.
    if not re.fullmatch(r"[A-Za-z0-9_-]{1,100}", nonce):
        return "Invalid nonce", 400

    # Count only valid GET browser-test requests. Flask also handles HEAD
    # automatically for GET routes, and Render/browser probes may issue HEAD.
    if request.method == "GET":
        record_cookie_test()

    nonce_js = json.dumps(nonce)
    origin_js = json.dumps(MAIN_ORIGIN)

    html = f"""<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>BB MOT Cookie Test</title>
</head>
<body>
<script>
(async () => {{
    const nonce = {nonce_js};
    const mainOrigin = {origin_js};
    const cookieName = "bbmot_third_party";
    const expectedCookie = `${{cookieName}}=${{nonce}}`;

    const cookieVisible =
        document.cookie
            .split("; ")
            .includes(expectedCookie);

    let storageAccess = null;

    if (typeof document.hasStorageAccess === "function") {{
        try {{
            storageAccess = await document.hasStorageAccess();
        }} catch (e) {{
            storageAccess = null;
        }}
    }}

    window.parent.postMessage(
        {{
            type: "bbmot-third-party-cookie",
            nonce: nonce,
            cookieVisible: cookieVisible,
            storageAccess: storageAccess
        }},
        mainOrigin
    );

    // Remove the temporary diagnostic cookie.
    document.cookie =
        `${{cookieName}}=; Max-Age=0; Path=/; SameSite=None; Secure`;
}})();
</script>
</body>
</html>"""

    response = make_response(html)

    response.set_cookie(
        "bbmot_third_party",
        nonce,
        max_age=60,
        secure=True,
        httponly=False,
        samesite="None",
        path="/"
    )

    response.headers["Cache-Control"] = "no-store"
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["Referrer-Policy"] = "no-referrer"
    response.headers["Content-Security-Policy"] = (
        "default-src 'none'; "
        "script-src 'unsafe-inline'; "
        "frame-ancestors https://blackboard-browser-mot.onrender.com"
    )

    return response


@app.get("/stats")
@stats_auth_required
def stats_dashboard():
    today = utc_day()

    with stats_lock:
        total = stats["cookie_tests_total"]
        today_total = stats["cookie_tests_by_day"].get(today, 0)
        started_at = stats["started_at"].strftime("%Y-%m-%d %H:%M:%S UTC")
        browsers = stats["browsers"].most_common()
        operating_systems = stats["operating_systems"].most_common()
        referrers = stats["referrers"].most_common()
        by_day = stats["cookie_tests_by_day"].most_common()

    def rows(items):
        if not items:
            return '<tr><td colspan="2">No data yet</td></tr>'

        return "".join(
            f"<tr><td>{label}</td><td>{count}</td></tr>"
            for label, count in items
        )

    html = f"""<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BB MOT Stats</title>
    <style>
        body {{
            font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
            max-width: 900px;
            margin: 2rem auto;
            padding: 0 1rem;
            color: #1f2937;
            background: #f8fafc;
        }}
        h1, h2 {{ color: #111827; }}
        .cards {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
            gap: 1rem;
            margin: 1.5rem 0;
        }}
        .card {{
            background: white;
            border: 1px solid #e5e7eb;
            border-radius: 12px;
            padding: 1rem;
        }}
        .value {{
            font-size: 2rem;
            font-weight: 700;
            margin-top: .25rem;
        }}
        .note {{
            color: #6b7280;
            font-size: .95rem;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            background: white;
            margin-bottom: 1.5rem;
        }}
        th, td {{
            text-align: left;
            padding: .7rem .8rem;
            border-bottom: 1px solid #e5e7eb;
        }}
        th:last-child, td:last-child {{
            text-align: right;
        }}
    </style>
</head>
<body>
    <h1>Blackboard Browser MOT stats</h1>

    <div class="cards">
        <div class="card">
            <div>Cookie tests today</div>
            <div class="value">{today_total}</div>
        </div>
        <div class="card">
            <div>Cookie tests since restart</div>
            <div class="value">{total}</div>
        </div>
    </div>

    <p class="note">
        Privacy-conscious aggregate counts only. No IP addresses or user IDs
        are stored. These figures reset whenever the app process restarts or
        is redeployed. A cookie-test request is a useful proxy for use of the
        main MOT page, but it is not a guaranteed count of unique people.
    </p>

    <h2>Browser</h2>
    <table>
        <thead><tr><th>Browser</th><th>Tests</th></tr></thead>
        <tbody>{rows(browsers)}</tbody>
    </table>

    <h2>Operating system</h2>
    <table>
        <thead><tr><th>OS</th><th>Tests</th></tr></thead>
        <tbody>{rows(operating_systems)}</tbody>
    </table>

    <h2>Referrer</h2>
    <table>
        <thead><tr><th>Source</th><th>Tests</th></tr></thead>
        <tbody>{rows(referrers)}</tbody>
    </table>

    <h2>By UTC day</h2>
    <table>
        <thead><tr><th>Date</th><th>Tests</th></tr></thead>
        <tbody>{rows(by_day)}</tbody>
    </table>

    <p class="note">Stats collection started: {started_at}</p>
</body>
</html>"""

    response = make_response(html, 200)
    response.headers["Cache-Control"] = "no-store"
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["X-Frame-Options"] = "DENY"
    return response

