from flask import Flask, request, make_response
import json
import re

app = Flask(__name__)

MAIN_ORIGIN = "https://blackboard-browser-mot.onrender.com"


@app.get("/")
def home():
    return "Blackboard Browser MOT cookie helper is running.", 200


@app.get("/cookie-test")
def cookie_test():
    nonce = request.args.get("nonce", "")

    # Only allow the nonce format generated by the MOT.
    if not re.fullmatch(r"[A-Za-z0-9_-]{1,100}", nonce):
        return "Invalid nonce", 400

    nonce_js = json.dumps(nonce)
    origin_js = json.dumps(MAIN_ORIGIN)

    html = f"""<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>BB MOT Cookie Test</title>
</head>
<body>
<script>
(async () => {{
    const nonce = {nonce_js};
    const mainOrigin = {origin_js};
    const cookieName = "bbmot_third_party";
    const expectedCookie = `${{cookieName}}=${{nonce}}`;

    const cookieVisible =
        document.cookie
            .split("; ")
            .includes(expectedCookie);

    let storageAccess = null;

    if (typeof document.hasStorageAccess === "function") {{
        try {{
            storageAccess = await document.hasStorageAccess();
        }} catch (e) {{
            storageAccess = null;
        }}
    }}

    window.parent.postMessage(
        {{
            type: "bbmot-third-party-cookie",
            nonce: nonce,
            cookieVisible: cookieVisible,
            storageAccess: storageAccess
        }},
        mainOrigin
    );

    // Remove the temporary diagnostic cookie.
    document.cookie =
        `${{cookieName}}=; Max-Age=0; Path=/; SameSite=None; Secure`;
}})();
</script>
</body>
</html>"""

    response = make_response(html)

    response.set_cookie(
        "bbmot_third_party",
        nonce,
        max_age=60,
        secure=True,
        httponly=False,
        samesite="None",
        path="/"
    )

    response.headers["Cache-Control"] = "no-store"
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["Referrer-Policy"] = "no-referrer"
    response.headers["Content-Security-Policy"] = (
        "default-src 'none'; "
        "script-src 'unsafe-inline'; "
        "frame-ancestors https://blackboard-browser-mot.onrender.com"
    )

    return response
